module.exports = [
  {
    id: 'why-i-chose-a-doctor-not-a-politician',
    date: '2026-05-25',
    title: 'Why I Chose a Doctor, Not a Politician',
    subtitle: 'The protagonist question — and why the answer changed everything about how this novel could be written.',
    category: 'craft',
    readingMinutes: 5,
    body: `Every political novel I have read puts a politician at the centre. They are inside the system. They know the grammar. They know which doors to knock on and which ones to never open.\n\nDr. Sampath Kumar is not a politician. He is an oncologist. He reads a governance crisis the same way he reads a scan — with no sentimental attachment to the diagnosis.\n\nWhen I decided this story would be told through a doctor's eyes, three things immediately changed. First, the corruption stopped being abstract. Corruption arrives in this novel as a tumour: it has blood supply, it has staging, it responds to specific treatments and resists others. The medical metaphor is not decoration — it is the novel's operating system.\n\nSecond, Sampath can name things without flinching. Politicians cannot say "this is wrong" without first asking "who does saying this serve?" Sampath asks only: "what does the scan show?" That clinical grammar gives the novel a moral voice that a political insider could never have.\n\nThird, and most importantly for scale — a doctor protagonist is universally legible. Every Indian family has had a doctor who told them something they did not want to hear. We know what that face looks like. We know what integrity in that profession costs. Sampath is not a Delhi insider. He is the person we would all want making the decision.\n\nThe question I keep returning to as I write: what is the actual measure of an honest man's success in a system designed to punish honesty? Not whether he transforms the system. Whether he demonstrates that transformation was possible. That is the only honest ending.`,
    createdAt: '2026-05-25T08:00:00.000Z',
    updatedAt: '2026-05-25T08:00:00.000Z',
  },
  {
    id: 'on-research-and-the-36000-crore-number',
    date: '2026-05-22',
    title: 'On Research and the Rs. 36,000 Crore Number',
    subtitle: "Where that figure comes from, why it had to be in the novel, and what writing from documented reality does to a story's credibility.",
    category: 'research',
    readingMinutes: 6,
    body: `The Rs. 36,000 crore number is not invented. I did not sit down and think "what sounds big enough to be dramatic?" I found it in the documented history of Karnataka's administrative challenges — in reports, in committee findings, in the kind of footnotes that career bureaucrats put into documents they know no one reads.\n\nWhen a novelist uses a real number, something happens to the reader's trust. They stop being a passenger and become a witness. They are no longer watching a story unfold — they are watching a record.\n\nThis is why the research phase of this novel cannot be rushed. Every incident in this book — the fabricated audio clip, the coffee plantation reclassification, the structure of the bribe offer — is built on documented real-world patterns. Not copy-pasted from headlines. Patterned from documented reality and then fictionalised into a specific story. That gap — between documented pattern and specific story — is where the novel lives.\n\nRamenahalli and I have talked about this at length. His concern, and mine, is not authenticity for its own sake. It is credibility at scale. A ₹1,000Cr film cannot afford a moment where a knowledgeable viewer thinks "that's not how Karnataka's administrative machinery works." One such moment breaks the spell. The research is not pedantry. It is insurance for the imagination.\n\nThe current chapter I am working on — the coffee plantation fraud — requires me to understand how agricultural zone reclassification actually functions under Karnataka's land revenue system. I spent four days on this last week before writing a single line. The four days do not show in the prose. That is exactly the point.`,
    createdAt: '2026-05-22T08:00:00.000Z',
    updatedAt: '2026-05-22T08:00:00.000Z',
  },
  {
    id: 'what-scale-does-to-a-story',
    date: '2026-05-19',
    title: 'What Scale Does to a Story',
    subtitle: 'Why writing for a ₹1,000Cr audience and writing for 1,000 readers require exactly the same discipline — but for opposite reasons.',
    category: 'process',
    readingMinutes: 4,
    body: `People assume that writing for scale means simplifying. Make the protagonist more likeable. Reduce the political complexity. Add a love story that softens the edges. Every person who has ever taken a serious political novel and "developed" it into a film has made at least three of these compromises. Usually more.\n\nRamenahalli's instruction to me — and this is the reason I trust him — was the opposite. He said: finish the novel at the highest level of difficulty the story demands. Do not write toward a hypothetical audience. Write toward the truth of these characters and this situation. Scale takes care of itself when the material is real.\n\nI think about this every morning when I sit down to write. The chapter I am in right now is Act II, Chapter 10. Sampath is watching a fabricated audio clip of himself on television. He does not react with rage. He picks up a pen and starts taking notes. That reaction — clinical documentation in the face of a personal attack — is the most politically radical thing in the novel. It is also not commercially obvious. A more commercially obvious protagonist would make calls, threaten people, fight back.\n\nBut scale — real scale, the kind that makes a film travel — comes from recognition. And what audiences recognise, in Karnataka, in Delhi, in every state where they have watched honest people be targeted, is that the most dangerous thing you can do is stay calm and write it down. That recognition is worth more than any plot escalation.\n\nI am writing toward that recognition. Not toward an audience. The distinction is everything.`,
    createdAt: '2026-05-19T08:00:00.000Z',
    updatedAt: '2026-05-19T08:00:00.000Z',
  },
  {
    id: 'the-climax-problem',
    date: '2026-05-15',
    title: 'The Climax Problem',
    subtitle: 'Why the ending of this novel is the hardest sentence I have ever had to write — and why I am not ready to write it alone.',
    category: 'process',
    readingMinutes: 5,
    body: `I know how this story ends. I have known since before I wrote the first chapter. The ending is not a plot question — Sampath's tenure concludes, Karnataka returns to electoral politics, the system resets. That is not a spoiler. That is announced in the novel's premise.\n\nThe hard question is not what happens. It is what it means.\n\nDoes the novel end in exhaustion? In quiet dignity? In something that reads as defeat to one reader and as proof-of-concept to another? These are not the same ending even if the events are identical. The last ten pages of a novel make retroactive meaning out of every page before them. Getting those ten pages wrong would not just ruin the ending — it would undo the whole argument.\n\nThis is why I want the founding 1,000 readers to be part of this conversation before I write the final chapter. Not to crowd-source the ending. To test whether the argument I have been building — that ordinary integrity, applied with extraordinary discipline, is its own form of victory — is landing the way I intend it to land.\n\nThere is a version of this ending that is falsely optimistic. There is a version that is gratuitously bleak. The version I am trying to write is neither. It is what I would call honest realism: the patient is not cured, but the patient is alive, and the doctor has proved that the treatment works. That is a harder emotional note to land than either triumph or defeat. I need readers who have been inside this story from the beginning to tell me if I am landing it.\n\nThis is the conversation I am building this community to have.`,
    createdAt: '2026-05-15T08:00:00.000Z',
    updatedAt: '2026-05-15T08:00:00.000Z',
  },
  {
    id: 'priyadarshini-the-character-i-underestimated',
    date: '2026-05-11',
    title: 'Priyadarshini — The Character I Underestimated',
    subtitle: "How Sampath's wife became the moral weight-bearing wall of the novel, and why she nearly disappeared from it entirely.",
    category: 'craft',
    readingMinutes: 4,
    body: `In the first draft of my outline, Priyadarshini appeared in three scenes. She was Sampath's anchor — the person who waited at home, who kept his private life intact while his public life became a siege. She was important but functional.\n\nThen I read back what I had written about Sampath's domestic life and realised: I had described a saint. And saints are not interesting. They are not even fair.\n\nPriyadarshini is a woman who did not ask for any of this. She did not choose public life. She did not sign up for the scrutiny, the threats to their family, the fabricated media coverage, the social cost of being married to the most controversial administrator in Karnataka. She is brilliant in her own right — her perspective on Sampath's choices is often sharper than his own. And I had reduced her to a supportive presence.\n\nThe craft assessment of this manuscript from our AI analysis was direct about it: Priyadarshini needs at least two additional scenes. She carries the novel's domestic weight but appears in only four chapters.\n\nI am adding those scenes now. Not as plot — as argument. Priyadarshini embodies what the novel calls "the invisible domestic toll of public courage." Her experience is the private tax on everything Sampath's integrity costs. Without her fully on the page, the novel's argument is incomplete. It becomes about a man who paid a price — rather than about a family that paid it together without ever being asked.\n\nThat is a different, smaller story. I am not writing that story.`,
    createdAt: '2026-05-11T08:00:00.000Z',
    updatedAt: '2026-05-11T08:00:00.000Z',
  },
  {
    id: 'why-democracy-is-the-right-subject-for-kannada-cinema',
    date: '2026-05-07',
    title: 'Why Democracy Is the Right Subject for Kannada Cinema Right Now',
    subtitle: 'On the specific cultural and political moment that makes this story possible — and why timing in literature is not opportunism.',
    category: 'democracy',
    readingMinutes: 6,
    body: `I want to address something I have been asked several times by people who have read the premise: is this story timely, or is it just topical? There is a difference. Topical stories exploit a news cycle. Timely stories speak to a condition that has been building for years and is only now legible to a wide audience.\n\nThe President's Rule is timely. Let me explain why carefully.\n\nKarnataka has had three coalition governments collapse in under eight months in this story. This is not invented political instability — it is a pattern that every Indian who follows state politics recognises. The instability is not the story. The story is: what kind of person does the state turn to when its own political class has failed it? And what does that person do when the system responds not with gratitude but with every tool of institutional pressure it possesses?\n\nThat question — what does integrity cost in a broken system? — is not a Bangalore question. It is not a Karnataka question. It is the question that every young Indian professional who has tried to do their job honestly in any institutional context has already lived. They know the answer from their own careers. This novel gives that answer a name, a face, and a dramatic argument.\n\nRamenahalli understood this immediately. He did not ask me to broaden the political setting or soften the institutional criticism. He asked me to make it more specific, not less. The specificity of Karnataka — Vidhana Soudha, the Western Ghats coffee estates, the specific textures of how Bengaluru's political economy operates — is what gives the story its credibility outside Karnataka. Specificity travels. Generality does not.\n\nThe youth of India are the audience I am writing for. Not because they are a demographic. Because they are the ones who will have to answer the question this novel asks.`,
    createdAt: '2026-05-07T08:00:00.000Z',
    updatedAt: '2026-05-07T08:00:00.000Z',
  },
  {
    id: 'the-1000-readers-and-why-i-need-you-now',
    date: '2026-05-03',
    title: 'The 1,000 Readers — and Why I Need You Now, Not Later',
    subtitle: 'An honest account of what the founding community means to the writing process — not as an audience, but as a reason the work stays honest.',
    category: 'community',
    readingMinutes: 4,
    body: `Most writers write in private and publish in public. The feedback loop is: finish → publish → hear from readers → regret two things you cannot change. I am trying to do something different, and I want to explain why.\n\nThis novel is being written in public — not in the sense that every draft is visible, but in the sense that the founding 1,000 readers are part of the conversation as the manuscript develops. You will read chapters as they are completed. You will participate in the climax conversation. You will be inside the process.\n\nI want to be clear about why I need this. It is not about validation. I am not asking you to tell me the novel is good. I am asking you to be the pressure that keeps it honest.\n\nWhen a writer works alone, there is a constant temptation to soften the difficult parts. To make Sampath more immediately sympathetic. To give the antagonist less genuine intelligence. To resolve the ambiguity in the ending because ambiguity makes readers uncomfortable. These are all compromises I can talk myself into at 2am when a chapter is not working.\n\nThe founding 1,000 are my resistance to that. Not because you will read every draft — you will not. But because I am writing knowing that 1,000 people who have invested real attention into this story will eventually read what I produce. That awareness changes what I am willing to accept on the page.\n\nThis is not a conventional pre-order. It is a form of creative accountability. And it is the reason the Sunday Cinemas model works — the writer is not alone, and the community is not passive.\n\nThank you for being here before the novel is finished. That is the part that matters.`,
    createdAt: '2026-05-03T08:00:00.000Z',
    updatedAt: '2026-05-03T08:00:00.000Z',
  },
];
